### PR TITLE
Override default notifyChanges behavior

### PR DESCRIPTION
**Pull request by frapontillo**
If there's the need to make different insert/update/replace queries, one would like to notify changes with `notifyChanges` only at the end of the whole process. As of now, changes are automatically notified at the end of each insert/update/delete.
By overriding the generated ContentProvider one could be able to override the default implementation.
Also, allowing the ContentProvider to be inherited from could let developers use some custom logic for join fake-Uris (which is something I'm doing) without having to manually edit the generated ContentProvider, by implementing that very logic in the inherited class.

### CODE REVIEW

**Comment by foxykeep** [comment]
Adding a flag to the json file to remove the final if you want.

About the notifyChanges, I don't think it's the way to go with the contentprovider. So I won't add it to the main repo.

**Comment by frapontillo** [comment]
Is there another way to suspend notifications on a Uri?

**Comment by foxykeep** [comment]
I was reading again your issue and after reading that :

"If there's the need to make different insert/update/replace queries, one would like to notify changes with notifyChanges only at the end of the whole process"

You should modify the client code (the one using the cursor) to not react to the modifications.
For example [ArrayAdapter](https://developer.android.com/reference/android/widget/ArrayAdapter.html) has a method called setNotifyOnChange to prevent the adapter from being updated while you are modifying it.

That's the right way to go I think

**Comment by foxykeep** [comment]
I've also added a "has_subclasses" flag in the input file to remove the final keyword from the generated Provider if you want.

**Comment by frapontillo** [comment]
Very good, I'll give it a try.
About the notification suspension, I am looking for a way to suspend notifications on the whole URI until the all of the queries are executed. Scenario: a URI is updated by an automatic updater service, and for each new entity a "replace" kind of query is made. Each insert/update will trigger the notification on all of the listeners, such as a regular `CursorAdapter` inside a generic `Activity`. Since the `Activity` is not controlling the "replace" queries, it won't know when to listen for changes.

**Comment by foxykeep** [comment]
No idea ... This is not in the perimeter of my Code Generator anymore :)

try to ask this specific question on stackoverflow ?

**Comment by frapontillo** [comment]
Done. http://stackoverflow.com/questions/15872621/disable-notifications-on-a-contentprovider-uri

**Comment by foxykeep** [comment]
If you get an answer, tell me. It's interesting to know :)

And I'll try to see if I can find some information

**Comment by foxykeep** [comment]
If you get an answer, tell me. It's interesting to know :)

And I'll try to see if I can find some information

Nicolas KLEIN aka Foxykeep

**Comment by frapontillo** [comment]
Thank you Nicolas, I will.

**Comment by writtmeyer** [comment]
I tend to disagree, Nicolas. See the implementations of CalendarContract or ContactsContract. Both take great care to _not_ notify when the Provider is in applyBatch-mode. 

See for example the [insert method of CalendarProvider2.java](http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android-apps/4.2.2_r1/com/android/providers/calendar/SQLiteContentProvider.java#SQLiteContentProvider.insert%28android.net.Uri%2Candroid.content.ContentValues%29).

The AndroidAPI provides no way for a client to deal with this. Not on CursorAdapter (you can only set a flag when constructing the Adapter) nor with Loaders - which are the recommended Android way to deal with content providers.

I agree, though, that this brings another problem down the road - one which [I've criticized on my blog](http://www.grokkingandroid.com/use-contentobserver-to-listen-to-changes/): Both ContentProviders don't notify the specific URI of the item(s) that has/have changed but only a generic URI. Sometimes that's no good (e.g. when the user has thousands of company contacts). I've even [filed an issue for this](https://code.google.com/p/android/issues/detail?id=39698) (for single updates/inserts not for batch-mode). Though no one seems to care about it.

**Comment by foxykeep** [comment]
Hmm didn't think of doing it like that ...

Let me find an 25th hour per day and see what I can do. I think I'll add another flag in the database definition to use this pattern if you want (most app don't really need that). If true, it will add a similar logic to not notify when applying batch of requests.

Sounds good ?

**Comment by frapontillo** [comment]
Sounds great, I may be able to find some time to work on this as well.
Thank you!

**Comment by writtmeyer** [comment]
Sounds very promising to me. And I think most apps that use the REST with ContentProvider pattern benefit from this.

**Comment by foxykeep** [comment]
I should be able to find some time this weekend to work on it.

**Comment by foxykeep** [comment]
I should be able to find some time this weekend to work on it.

Nicolas KLEIN aka Foxykeep

On Wed, Apr 10, 2013 at 9:00 AM, Wolfram Rittmeyer <notifications@github.com

**Pull request closed without merging**
